### ISSUE TITLE
Data visualization using matplotib or seaborn

### ISSUE THREAD

**Issue by Javali-M** [MSTC-DA-IICT/HacktoberFest22-Mess-with-ML#5]
This weather dataset can be visualized in different ways through bar graphs or pie charts.

**Comment by Javali-M** [comment]
Please assign this issue to me @harshpatel2212, I'll make sure to represent the data visually in different ways.

**Comment by harshpatel2212** [comment]
@Javali-M please provide updates on the issue.

**Comment by Javali-M** [comment]
@harshpatel2212 Yes I'm working on it, almost done I'll open the pull request by evening today.

**Comment by harshpatel2212** [comment]
@Javali-M You have not done the pull request yet!, And we would close the issue, we are here to manage this repository. Please don't repeat this behaviour.

**Comment by Javali-M** [comment]
I have opened the pull request already and it was even merged into the repo by @apran-vs
The #9 pull request is mine.

**Comment by Javali-M** [comment]
I learnt that one must close the issue if the requirement is satisfied. Since I had completed it and the issue was opened by me, I closed it once my pull request was merged into the project.
