### ISSUE TITLE
Add Decision Tree for weather Prediction!

### ISSUE THREAD

**Issue by patenvy1234** [MSTC-DA-IICT/HacktoberFest22-Mess-with-ML#6]
Using given attributes/columns in the dataset, train a decision tree to predict the weather.

**Comment by apran-vs** [comment]
What is the update on the issue @patenvy1234 ??

**Comment by harshpatel2212** [comment]
I would like to contribute to this issue. Please assign me.

**Comment by harshpatel2212** [comment]
Thank You!, I have done the PR, kindly verify it and merge it.
