### ISSUE TITLE
Laptop Price Prediction

### ISSUE THREAD

**Issue by Manasi2001** [MSTC-DA-IICT/HacktoberFest22-Mess-with-ML#8]
Hello!

I was like to contribute this project to your repository. I'll be including the dataset, an ipynb notebook, a README and a GUI file. Please assign it to me. Thanks!

**Comment by srikarpadaliya** [comment]
@Manasi2001 we encourage issues related to the current project. Please do not drop irrelevant issues also use the discussion section first if you want to add any issues.
